trip_ideas = ['greece', 'japan', 'london', 'paris', 'new york']
print(trip_ideas)
print(sorted(trip_ideas))
print(trip_ideas)
print(sorted(trip_ideas,reverse=True))
print(trip_ideas)
trip_ideas.reverse()
print(trip_ideas)
trip_ideas.reverse()
print(trip_ideas)
trip_ideas.sort()
print(trip_ideas)
trip_ideas.sort(reverse=True)
print(trip_ideas)